from abc import ABC, abstractmethod
from typing import Dict, Any, Optional, List


class BaseLLM(ABC):
    """Abstract base class for all LLM services."""

    def __init__(self, config: Dict[str, Any]):
        """
        Initialize the LLM service.

        Args:
            config: Dictionary with LLM configuration
        """
        self.config = config
        self.model = config.get('model')
        self.temperature = config.get('temperature', 0.7)
        self.max_tokens = config.get('max_tokens', 2000)

    @abstractmethod
    def generate(self, prompt: str, **kwargs) -> str:
        """
        Generate a response from the prompt.

        Args:
            prompt: Prompt to send to the LLM
            **kwargs: Additional parameters specific to the provider

        Returns:
            The response generated by the LLM
        """
        pass

    @abstractmethod
    def generate_with_history(
        self,
        messages: List[Dict[str, str]],
        **kwargs
    ) -> str:
        """
        Generate a response considering the message history.

        Args:
            messages: List of messages in [{"role": "user/assistant", "content": "..."}] format
            **kwargs: Additional parameters specific to the provider

        Returns:
            The response generated by the LLM
        """
        pass

    @abstractmethod
    def is_available(self) -> bool:
        """
        Check if the LLM service is available.

        Returns:
            True if available, False otherwise
        """
        pass

    def generate_with_tools(
        self,
        messages: List[Dict[str, str]],
        tools: List[Any],
        **kwargs
    ) -> str:
        """
        Generate a response using function calling with external tools.

        This method is optional - not all LLM providers support function calling.
        The default implementation raises NotImplementedError.

        Args:
            messages: List of messages in [{"role": "user/assistant", "content": "..."}] format
            tools: List of available Langchain tools
            **kwargs: Additional parameters

        Returns:
            The response generated by the LLM after potentially calling tools

        Raises:
            NotImplementedError: If the provider does not support function calling
        """
        raise NotImplementedError(
            f"{self.__class__.__name__} does not support function calling. "
            "Implement this method to enable the use of external tools."
        )

    def set_temperature(self, temperature: float) -> None:
        """Set the temperature for generation."""
        self.temperature = temperature

    def set_max_tokens(self, max_tokens: int) -> None:
        """Set the maximum number of tokens."""
        self.max_tokens = max_tokens

    def get_model_info(self) -> Dict[str, Any]:
        """
        Return information about the current model.

        Returns:
            Dictionary with model information
        """
        return {
            'provider': self.__class__.__name__,
            'model': self.model,
            'temperature': self.temperature,
            'max_tokens': self.max_tokens
        }
